
<?php if(!empty($slider)): ?>
<div class="flexslider <?=$slider['code']?>">
    <ul class="slides">
        <?php if(!empty($slider['items'])): ?>
            <?php foreach($slider['items'] as $item): ?>



            <?php
            if(!empty($item['fecha_inicio']) && $item['fecha_inicio'] !='0000-00-00')
            {
                if(strtotime(date('Y-m-d')) < strtotime($item['fecha_inicio']))
                {
                    continue;
                }
            }
            if(!empty($item['fecha_fin']) && $item['fecha_fin'] != '0000-00-00')
            {
                if(strtotime(date('Y-m-d')) > strtotime($item['fecha_fin']))
                {
                    continue;
                }
            } 
            ?>
                <li class="item_<?=$item['id']?>" >
                <?php if($item['tipo'] == 'imagen'): ?>
                <?php
                    $item['imagen'] = '';
                    $item['imagen_responsive'] = '';
                    if(!empty($item["file"]) && file_exists($MyConfigure->getServerUploadDir()."/sliders/".$item['id_slider']."/".$item["file"]))
                    {
                        $item['imagen'] = $MyConfigure->getUploadDir()."/sliders/".$item["id_slider"]."/".$item["file"];

                    }
                    if(!empty($item["file_responsive"]) && file_exists($MyConfigure->getServerUploadDir()."/sliders/".$item['id_slider']."/".$item["file_responsive"]))
                    {
                        $item['imagen_responsive'] = $MyConfigure->getUploadDir()."/sliders/".$item["id_slider"]."/".$item["file_responsive"];
                    }
                ?>
                <?php if(!empty($item['url'])): ?>
                    <a href="<?=$item['url']?>" target="blank" class="">
                <?php endif; ?>
                <?=makeHTMLImg($item['imagen_responsive'],"","",$item['titulo'],"data-mobile='".$item['imagen_responsive']."' data-desktop='".$item['imagen']."'"); ?>
                <?php if(!empty($item['url'])): ?>
                    </a>
                <?php endif; ?>    
                    <script>
                    $(window).load(function(){
                        if($(this).width() < 768)
                        {
                            if($('.item_<?=$item['id']?>').find('img').attr('data-mobile').length > 0)
                            {
                                $('.item_<?=$item['id']?>').find('img').attr('src',$('.item_<?=$item['id']?>').find('img').attr('data-mobile'));
                            }
                        }
                        else{
                            if($('.item_<?=$item['id']?>').find('img').attr('data-desktop').length > 0)
                            {
                                $('.item_<?=$item['id']?>').find('img').attr('src',$('.item_<?=$item['id']?>').find('img').attr('data-desktop'))
                            }
                        }
                    });
                    $(window).resize(function(){
                        if($(this).width() < 768)
                        {
                            if($('.item_<?=$item['id']?>').find('img').attr('data-mobile').length > 0)
                            {
                                $('.item_<?=$item['id']?>').find('img').attr('src',$('.item_<?=$item['id']?>').find('img').attr('data-mobile'));
                            }
                        }
                        else{
                            if($('.item_<?=$item['id']?>').find('img').attr('data-desktop').length > 0)
                            {
                                $('.item_<?=$item['id']?>').find('img').attr('src',$('.item_<?=$item['id']?>').find('img').attr('data-desktop'))
                            }
                        }
                    });
                    </script>
                <?php endif; ?>
                <?php if($item['tipo'] == 'video'): ?>
                    <?php
                    $item['video'] = "";
                    $item['video_responsive'] = "";
                    if(!empty($item["file"]) && file_exists($MyConfigure->getServerUploadDir()."/sliders/".$item['id_slider']."/".$item["file"]))
                    {
                        $item['video'] = $MyConfigure->getUploadDir()."/sliders/".$item["id_slider"]."/".$item["file"];

                    }
                    if(!empty($item["file_responsive"]) && file_exists($MyConfigure->getServerUploadDir()."/sliders/".$item['id_slider']."/".$item["file_responsive"]))
                    {
                        $item['video_responsive'] = $MyConfigure->getUploadDir()."/sliders/".$item["id_slider"]."/".$item["file_responsive"];
                    }
                    ?>

                    <video class="w_video" id="video_<?=$item['id']?>" loop="loop" muted="muted" playsinline="playsinline" width="100%" controls>
                        <source id="item_<?=$item['id']?>" src="<?=$item['video_responsive'];?>" data-mobile="<?=$item['imagen_responsive']?>" data-desktop="<?=$item['imagen']?>" />
                    </video>
                    <script>
                    var v<?=$item['id']?> = document.getElementById("video_<?=$item['id']?>");
                    $(window).load(function(){
                        if($(this).width() < 768)
                        {
                            if($('#item_<?=$item['id']?>').attr('data-mobile').length > 0)
                            {
                                $('#item_<?=$item['id']?>').attr('src',$('#item_<?=$item['id']?>').attr('data-mobile'));
                            }
                        }
                        else{
                            if($('#item_<?=$item['id']?>').attr('data-desktop').length > 0)
                            {
                                $('#item_<?=$item['id']?>').attr('src',$('#item_<?=$item['id']?>').attr('data-desktop'))
                            }
                        }
                        v<?=$item['id']?>.load();
                    });
                    $(window).resize(function(){
                        if($(this).width() < 768)
                        {
                            if($('#item_<?=$item['id']?>').attr('data-mobile').length > 0)
                            {
                                $('.item_<?=$item['id']?>').find('img').attr('src',$('.item_<?=$item['id']?>').find('img').attr('data-mobile'));
                            }
                        }
                        else{
                            if($('#item_<?=$item['id']?>').attr('data-desktop').length > 0)
                            {
                                $('.item_<?=$item['id']?>').find('img').attr('src',$('.item_<?=$item['id']?>').find('img').attr('data-desktop'))
                            }
                        }
                        v<?=$item['id']?>.load();
                    });
                    </script>
                <?php endif; ?>
                <?php if($item['tipo'] == 'video-embebed'): ?>
                    <div class="videoWrapper">
                        <?=$item['code']?>
                    </div>
                <?php endif; ?>

                <?php if(!empty($item['titulo']) || !empty($item['descripcion']) || !empty($item['url'])): ?>
                    <div class="<?=(!empty($item['titulo']) || !empty($item['descripcion']) ? '_cont_txt_slider' : (!empty($item['boton_link']) ?'_simple_button' : ''))?>">
                        <?php if(!empty($item['titulo'])): ?>
                            <h2><?=$item['titulo']?></h2>
                        <?php endif; ?>
                        <?php if(!empty($item['descripcion'])): ?>
                        <p><?=$item['descripcion']?></p>
                        <?php endif; ?>
                        <?php if(!empty($item['url']) && !empty($item['boton_link'])): ?>
                            <a href="<?=$item['url']?>" target="blank" class="_btn _primary">Ver mas</a>
                        <?php endif; ?>
                    </div>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            <?php endif; ?>
    </ul>
</div>
<script>
    $(window).load(function() {
        $('.<?=$slider['code']?>').flexslider({
            controlNav: <?=($slider['controlnav'] == 1 ? 'true' : 'false')?>,
            animationLoop: <?=($slider['infinito'] == 1 ? 'true' : 'false')?>,
            slideshow: <?=($slider['auto'] == 1 ? 'true' : 'false')?>,
        });
    });
</script>
<?php endif; ?>
