<div class="w-xxxx-12">
    <div class="content">
        <h1 class="align_center"></h1>
        <h3 class="align_center"></h3>
        <?php echo $adminForm->openTag(); ?>
        <?php  echo $adminForm->get("callback"); ?>


        <?php if(!empty($id)): ?>
        <?php  echo $adminForm->get("id"); ?>
          <?php endif; ?>
        <?php  echo $adminForm->getRow("name"); ?>
        <?php  echo $adminForm->getRow("code"); ?>

       

        <?php  echo $adminForm->getRow("controlnav"); ?>
        <?php  echo $adminForm->getRow("auto"); ?>
        <?php  echo $adminForm->getRow("infinito"); ?>
        

        <?php  echo $adminForm->getRow("guardar"); ?>

        <?php echo $adminForm->endTag(); ?>

    </div>

  

</div>



<script >
$(document).ready(function()
{
  $( "#frmsliders" ).validate();
});
</script>